
source 'http://192.168.5.103/root/taihe_spec_ios.git' # 私有库地址
source 'https://github.com/CocoaPods/Specs.git' # 官方地址

use_frameworks!

plugin 'cocoapods-art', :sources => [
    'cocoapods-remote-company'
]

target 'STWebImage_Example' do
  pod 'STWebImage', :path => '../'

  target 'STWebImage_Tests' do
    inherit! :search_paths

    
  end
end
